### ISSUE TITLE
Profile on mouseover of user handle

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#28]
Show profile on mouseover, allow following, blocking, rating with comment etc.

**Comment by janaagaard75** [comment]
I think Member should avoid things that overlay and avoid using hover, because it doesn’t work well on touch screens.

**Comment by FreeTrade** [comment]
Mouseover additional information is useful though - it's often interesting to see who has liked a post, or given tips, or give quick links to interact with a profile. How this is displayed maybe a matter for the presentation, so on desktop, styling might use hover, and mobile might require a click to display the info.

**Comment by janaagaard75** [comment]
I definitely agree that the information is useful. What I am proposing is just to avoid using a tooltip, since that will require a tab on the screen on touch devices - as you mention yourself - and that will give touch devices a sort of second class interfaces. I think it would be better to always require a click, and then make sure that the site loads fast enough, so that this isn't an issue. Just my two cents. 🙂

**Comment by FreeTrade** [comment]
Can you explain 'tab on the screen' - I'm not quite following. How do you like how Memo handles this? (mouse over on desktop, click on mobile)

**Comment by janaagaard75** [comment]
Sorry. What I meant was ‘tap on screen’, that is ‘click on the screen with the finger’.

As you can probably tell, I am not fund of Memo’s interface. I would prefer if the profile details always requires a click, and that this click would link to the profile page instead of showing a pop-up. In the same fashion, I would also prefer if Memo linked to post-threads instead of showing them in pop-ups. Twitter also use these pop-ups, so I assume that this is why Memo introduced them too.

**Comment by Real-FEELS** [comment]
IMO: 
- Desktop on hover should be fine (memo and twitter do this)
- For mobile devices a click would be better.

**Comment by Real-FEELS** [comment]
@FreeTrade 
Wrap the _Image/identicon, name and starrrating_  into a div with a class called `profile-meta`

Wrap the _profile text_ in a div with a class called `profile-text`

Wrap the _following_ and _followers_ in a div with a class called `profile-actions`

**Comment by FreeTrade** [comment]
>     * For mobile devices a click would be better.

If we bring up the card on click for a mobile, what is a good way for the user to dismiss the card?

**Comment by Real-FEELS** [comment]
Either selecting outside the card to close it or adding an X to the popover

Alternatively you could disable it on mobile.

**Comment by janaagaard75** [comment]
>> If we bring up the card on click for a mobile, what is a good way for the user to dismiss the card?
>
> Either selecting outside the card to close it or adding an X to the popover

On a mobile device it's better to support navigating back, because that's built in to the browser - you simply swipe on the screen.

**Comment by Real-FEELS** [comment]
@FreeTrade 
Please add the following classes
- `member-handle` to the users @handle 
- `member-name` to the users Name

**Comment by FreeTrade** [comment]
Added, but as member-handle, and member-pagingid - i'd confused the terms.

**Comment by FreeTrade** [comment]
For now, i think we'll stick with click on mobile going direct to users full profile page. This is the same behavior as Twitter, and saves some complication.
One small bug on desktop. I've added a delay to popup appearance, but if i click intending to visit profile page, but popup appears in the meantime, the click doesn't do anything. Better if the element under the pointer has the same behaviour pre/post popup. Can fix by moving the popup up slightly.

**Comment by Real-FEELS** [comment]
@FreeTrade  `profilepreviewfollowbutton` should be inside of the profile-actions div. 

Also the profile image is not displaying on the card. 

If you already follow a user. `Follow` should change to `unfollow`
